server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: USERINFO

  datasource:
    url: jdbc:postgresql://192.168.0.188:5432/postgres
    username: duytc
    password: duytc
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      idle-timeout: 20000
      maximum-pool-size: 2
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: Pool ==>

  liquibase:
    change-log: classpath:/liquibase/main-changelog.yml
    clear-checksums: true
    contexts: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.userinfomanager.requests, com.example.userinfomanager.responses
  mapper-locations: /mybatis/*.xml
