# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: |
          echo "gpr.user=duytc1811" >> gradle.properties
          echo "gpr.key=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" >> gradle.properties
          ./gradlew clean build --exclude-task test

#      - name: Build and Push Docker Image
#        run: |
#          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
#          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/user-info-service:latest
#          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-info-service:latest