# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
                "id": "DuyTC1811-common",
                "url": "https://maven.pkg.github.com/DuyTC1811/common",
                "username": "${{ secrets.CUSTOM_REPO_USERNAME }}",
                "password": "${{ secrets.CUSTOM_REPO_PASSWORD }}"
            }]


      - name: Build with Gradle | Build and Push Docker Image
        run: |
          ./gradlew clean build --exclude-task test
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/user-info-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-info-service:latest